apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: dev-backend-config
  namespace: dev
spec:
  timeoutSec: 600
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
  sessionAffinity:
    affinityType: "NONE"
  cdn:
    enabled: false
