apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "*.process-gpt.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: process-gpt-execution-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "execution.process-gpt.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: process-gpt-execution-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autonomous-ingress
spec:
  rules:
  - host: autonomous.process-gpt.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: autonomous-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memento-ingress
spec:
  rules:
  - host: memento.process-gpt.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: memento-service
            port:
              number: 80