apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "*.process-gpt.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: execution-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "execution.process-gpt.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: execution-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autonomous-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/upgrade-websocket: "true"
spec:
  rules:
  - host: autonomous.process-gpt.io
    http:
      paths:
      - pathType: Prefix
        path: "/ws"
        backend:
          service:
            name: autonomous-service
            port:
              number: 6789
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memento-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: memento.process-gpt.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: memento-service
            port:
              number: 80