apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: process-gpt-gateway
  namespace: default
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    port: 443
    protocol: HTTPS
    hostname: "*.process-gpt.io"
    tls:
      mode: Terminate
      certificateRefs:
      - name: process-gpt-tls
        kind: Secret
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.process-gpt.io"
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: process-gpt-gateway-root
  namespace: default
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https-root
    port: 443
    protocol: HTTPS
    hostname: "process-gpt.io"
    tls:
      mode: Terminate
      certificateRefs:
      - name: process-gpt-tls
        kind: Secret
  - name: http-root
    port: 80
    protocol: HTTP
    hostname: "process-gpt.io"
    allowedRoutes:
      namespaces:
        from: All 