apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 5173
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: execution-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: execution
---
apiVersion: v1
kind: Service
metadata:
  name: autonomous-service
spec:
  type: LoadBalancer
  selector:
    app: autonomous
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: memento-service
spec:
  type: LoadBalancer
  selector:
    app: memento
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005